version: '3'

volumes:
  pg_data:
  static:
  media:
services:
  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: foodgram_backend
    image: noupsange/foodgram_backend:latest
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/app/foodgram_backend/media
    depends_on:
      - db
    restart: always
  frontend:
    container_name: foodgram_frontend
    env_file: ../.env
    image: noupsange/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles
      - media:/var/www/foodgram
      - type: bind
        source: ../frontend/build
        target: /app/frontend/build
    depends_on:
      - backend
    restart: always