volumes:
  pg_data:
  static:
  media:
services:
  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: foodgram_backend
    image: noupsange/foodgram_backend:latest
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/app/foodgram_backend/media
    depends_on:
      - db
    restart: always
  frontend:
    container_name: foodgram_frontend
    env_file: ../.env
    image: noupsange/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    container_name: foodgram-proxy
    image: noupsange/foodgram_nginx:latest
    ports:
      - 80:80
    volumes:
      - static:/staticfiles
      - media:/var/www/foodgram
    depends_on:
      - backend
    restart: always